### ISSUE TITLE
CSRF middleware exception needed for some endpoint

### ISSUE THREAD

**Issue by gaud2029** [whitecube/laravel-cookie-consent#18]
the accept-all and essentials are using content-type text/html.  it's not inject any csrf token information in the call so the calls is redirected with a 302.  

You need to add these endpoint  to the csrf middleware exceptions list.

**Comment by toonvandenbos** [comment]
Hi @gaud2029,

Could you elaborate? Thanks.

**Comment by gaud2029** [comment]
I cannot reproduce the problem I had anymore so I guess this can be closed.

Basically some request were made as "application/json" and some other were made as "text/html" 

I was having a 302 redirect and noticed that the request went through when I was adding those endpoint to the CSRF middleware exceptions array.

The only endpoint that was working was the "configure" endpoint.
