### ISSUE TITLE
While accpet-all then display error.

### ISSUE THREAD

**Issue by nikunjakbari07** [whitecube/laravel-cookie-consent#20]
![image](https://github.com/whitecube/laravel-cookie-consent/assets/136449824/b308a3b1-8fae-4021-8c81-491bcd33ce3a)
While accept-all button clicked then display this type of error it's only accept all button not for Only essentials.
pls help me for same

**Comment by gaud2029** [comment]
remove the "darkmode_enabled" cookie declaration, it's only meant to be an example.

**Comment by nikunjakbari07** [comment]
Okay grate it's working fine thanks
