### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by jeffdv** [whitecube/laravel-cookie-consent#37]
Please update for laravel 11

**Comment by voidgraphics** [comment]
https://github.com/whitecube/laravel-cookie-consent/releases/tag/v1.2.0

**Comment by Jaspur** [comment]
@voidgraphics 

>   - whitecube/laravel-cookie-consent v1.2.0 requires laravel/framework ^9|^10|^11 -> satisfiable by laravel/framework[v11.0.0, ..., 11.x-dev].
>     - Conclusion: don't install laravel/framework v11.0.0 (conflict analysis result)
