### ISSUE TITLE
Method Whitecube\LaravelCookieConsent\CookiesRegistrar::accessibility does not exist

### ISSUE THREAD

**Issue by danielveselinov** [whitecube/laravel-cookie-consent#4]
I would like to open an issue regarding to method that appears it doesn't exits.

Following instructions as mentioned in the documentation after I try to register the cookies into boot() method it throws error exception that the method accessibility() doesn't exits.

```
Laravel Version - 10.13.5  
PHP Version - 8.2.7  
Composer Version - 2.5.5 
```

**Comment by toonvandenbos** [comment]
Hi @danielveselinov, as explained in the documentation, you should create the missing categories yourself. By default, only the essentials, analytics and optional categories exist.

Use the `Cookies::category()` method to register your custom categories.
