### ISSUE TITLE
class Whitecube\LaravelCookieConsen\Cookie

### ISSUE THREAD

**Issue by eldIsher** [whitecube/laravel-cookie-consent#7]
No easy possibility to change properties of class Whitecube\LaravelCookieConsen\Cookie
  https://github.com/whitecube/laravel-cookie-consent#cookie-policy-details-page
   $cookie->description  is empty and cannot be easily set

**Comment by toonvandenbos** [comment]
Hi, attributes can be easily defined as follows: https://github.com/whitecube/laravel-cookie-consent#custom-cookie-attributes
